spring.application.name=DINO-API
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.address=0.0.0.0
server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dinoappverify@gmail.com
spring.mail.password=bsrelnlbtkxhdmhe
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.gvmikifiduavqopxlucf
spring.datasource.password=CZqPqr9kTjKn7fdn
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=30000
spring.datasource.hikari.connection-timeout=20000

spring.devtools.restart.enabled=false
